const getImageSource = (symbol) => {
  if (!symbol) {
    return require('../assets/icons/crypto/other.png').default;
  }
  if (symbol === 'USDC/ODOP') {
    return require('../assets/icons/crypto/odop.png').default;
  }
  if (symbol?.includes('/')) {
    symbol = symbol.split('/')[0];
  }
  switch (symbol) {
    // Crypto
    case 'BTC':
      return require('../assets/icons/crypto/btc.png').default;
    case 'ETH':
      return require('../assets/icons/crypto/eth.png').default;
    case 'LINK':
      return require('../assets/icons/crypto/link.png').default;
    case 'ETC':
      return require('../assets/icons/crypto/etc.png').default;
    case 'EOS':
      return require('../assets/icons/crypto/eos.png').default;
    case 'LTC':
      return require('../assets/icons/crypto/ltc.png').default;
    case 'BCH':
      return require('../assets/icons/crypto/bch.png').default;
    case 'BNB':
      return require('../assets/icons/crypto/bnb.png').default;
    case 'BSV':
      return require('../assets/icons/crypto/bsv.png').default;
    case 'XTZ':
      return require('../assets/icons/crypto/xtz.png').default;
    case 'XRP':
      return require('../assets/icons/crypto/xrp.png').default;
    case 'ALGO':
      return require('../assets/icons/crypto/algo.png').default;
    case 'MATIC':
      return require('../assets/icons/crypto/matic.png').default;
    case 'OKB':
      return require('../assets/icons/crypto/okb.png').default;
    case 'HT':
      return require('../assets/icons/crypto/ht.png').default;
    case 'ATOM':
      return require('../assets/icons/crypto/atom.png').default;
    case 'TRX':
      return require('../assets/icons/crypto/trx.png').default;
    case 'ADA':
      return require('../assets/icons/crypto/ada.png').default;
    case 'USDT':
      return require('../assets/icons/crypto/usdt.png').default;
    case 'DRGN':
      return require('../assets/icons/crypto/drgn.png').default;
    case 'DOGE':
      return require('../assets/icons/crypto/doge.png').default;
    case 'TOMO':
      return require('../assets/icons/crypto/tomo.png').default;
    case 'BTMX':
      return require('../assets/icons/crypto/btmx.png').default;
    case 'TRYB':
      return require('../assets/icons/crypto/tryb.png').default;
    case 'LEO':
      return require('../assets/icons/crypto/leo.png').default;
    case 'FTT':
      return require('../assets/icons/crypto/ftt.png').default;
    case 'FTT_R3':
      return require('../assets/icons/crypto/ftt.png').default;
    case 'FTT_TT1':
      return require('../assets/icons/crypto/ftt.png').default;
    case 'FTT_TT2':
      return require('../assets/icons/crypto/ftt.png').default;
    case 'USD':
      return require('../assets/icons/crypto/usd.png').default;
    case 'EUR':
      return require('../assets/icons/crypto/eur.png').default;
    case 'BRZ':
      return require('../assets/icons/crypto/brz.png').default;
    case 'BRL':
      return require('../assets/icons/crypto/brl.png').default;
    case 'KNC':
      return require('../assets/icons/crypto/knc.png').default;
    case 'WRX':
      return require('../assets/icons/crypto/wrx.png').default;
    case 'THETA':
      return require('../assets/icons/crypto/theta.png').default;
    case 'XAUT':
      return require('../assets/icons/crypto/xaut.png').default;
    case 'COMP':
      return require('../assets/icons/crypto/comp.svg').default;
    case 'BAL':
      return require('../assets/icons/crypto/bal.svg').default;
    case 'TRUMPWIN':
      return require('../assets/icons/crypto/trumpwin.png').default;
    case 'TRUMPLOSE':
      return require('../assets/icons/crypto/trumplose.png').default;
    case 'SRM':
      return require('../assets/icons/crypto/srm.png').default;
    case 'MSRM':
      return require('../assets/icons/crypto/msrm.svg').default;
    case 'SRM_LOCKED':
      return require('../assets/icons/crypto/srm.png').default;
    case 'MSRM_LOCKED':
      return require('../assets/icons/crypto/msrm.svg').default;
    case 'SXP':
      return require('../assets/icons/crypto/sxp.png').default;
    case 'SOL':
      return require('../assets/icons/crypto/sol.png').default;
    case 'YFI':
      return require('../assets/icons/crypto/yfi.svg').default;
    case 'RUNE':
      return require('../assets/icons/crypto/rune.png').default;
    case 'AMPL':
      return require('../assets/icons/crypto/ampl.png').default;
    case 'WBTC':
      return require('../assets/icons/crypto/wbtc.png').default;
    case 'MKR':
      return require('../assets/icons/crypto/mkr.png').default;
    case 'DMG':
      return require('../assets/icons/crypto/dmm.png').default;
    case 'UBXT':
      return require('../assets/icons/crypto/ubxt.png').default;
    case 'UNI':
      return require('../assets/icons/crypto/uni.png').default;
    case 'AAVE':
      return require('../assets/icons/crypto/aave.svg').default;
    case 'CREAM':
      return require('../assets/icons/crypto/cream.png').default;
    case 'HGET':
      return require('../assets/icons/crypto/hdget.png').default;
    case 'HNT':
      return require('../assets/icons/crypto/hnt.png').default;
    case 'MTA':
      return require('../assets/icons/crypto/mstable.png').default;
    case 'SUSHI':
      return require('../assets/icons/crypto/sushi.png').default;
    case 'FRONT':
      return require('../assets/icons/crypto/front.png').default;
    case 'ALEPH':
      return require('../assets/icons/crypto/aleph.png').default;
    case 'OMG':
      return require('../assets/icons/crypto/omg.png').default;
    case 'AKRO':
      return require('../assets/icons/crypto/akro.png').default;
    case 'LUA':
      return require('../assets/icons/crypto/lua.png').default;
    case 'MATH':
      return require('../assets/icons/crypto/math.png').default;
    case 'HXRO':
      return require('../assets/icons/crypto/hxro.jpg').default;
    case 'KEEP':
      return require('../assets/icons/crypto/keep.jpg').default;
    case 'FIDA':
      return require('../assets/icons/crypto/fida.svg').default;
    case 'LQID':
      return require('../assets/icons/crypto/lqid.svg').default;
    case 'USDC':
      return require('../assets/icons/crypto/usdc.svg').default;
    case 'RSR':
      return require('../assets/icons/crypto/rsr.svg').default;
    case 'CEL':
      return require('../assets/icons/crypto/cel.svg').default;
    case 'PAXG':
      return require('../assets/icons/crypto/paxg.svg').default;
    case '1INCH':
      return require('../assets/icons/crypto/1inch.png').default;
    case 'GRT':
      return require('../assets/icons/crypto/grt.svg').default;
    case 'KIN':
      return require('../assets/icons/crypto/kin.png').default;
    case 'MAPS':
      return require('../assets/icons/crypto/maps.svg').default;
    case 'PERP':
      return require('../assets/icons/crypto/perp.png').default;
    case 'RAY':
      return require('../assets/icons/crypto/ray.svg').default;
    case 'RAYPOOL':
      return require('../assets/icons/crypto/ray.svg').default;

    // Default
    default:
      return require('../assets/icons/crypto/other.png').default;
  }
};

export default getImageSource;
